
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef SPICE_WIDGET_ENUMS_H
#define SPICE_WIDGET_ENUMS_H

G_BEGIN_DECLS
#define SPICE_TYPE_DISPLAY_KEY_EVENT spice_display_key_event_get_type()
GType spice_display_key_event_get_type (void);
G_END_DECLS

#endif /* SPICE_WIDGET_ENUMS_H */

/* Generated data ends here */

